language: python
cache: pip

python:
    - "2.7"

# install jupyter and get reveal.js as we will need it to build the website
# from Travis
install:
    - pip install jupyter
    - wget https://github.com/mccoy04041991/CampaignContributionDemoCode.git
    - mv CampaignContributionDemoCode.git CampaignContributionDemoCode

script:
    - jupyter notebook --no-browser